#!/usr/bin/env python


import random


# Create Guessing Game class that creates a random number
# between 0 and 10. Check if user input is equal to the
# random number. If not continue to ask user for a number
# until the input is equal to the randomly generated number.


class GuessingGame():

    pass
    # Create an __init__ method which will generate a random number upon instantiation of class


    # Create class method to reset the __init__ method's random number with a new random number

    
    # Create a class method that takes user input and compares it to the randomly generated number.
    # If the number entered does not equal the random number, ask user to input another number,
    # and let the user know if the correct number is higher or lower than randomly generated number.
    # Repeate this process until user enters a number equal to the randomly generated number.



# Create simple test function for the GuessingGame class

def test():
    pass



    